In [5]:
import nflreadpy as nfl

injuries = nfl.load_injuries(seasons=[2024])
depth_charts = nfl.load_depth_charts(seasons=[2024])

In [4]:
injuries

shape: (6_215, 16)
┌────────┬───────────┬──────┬──────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ season ┆ game_type ┆ team ┆ week ┆ … ┆ practice_pri ┆ practice_sec ┆ practice_sta ┆ date_modifie │
│ ---    ┆ ---       ┆ ---  ┆ ---  ┆   ┆ mary_injury  ┆ ondary_injur ┆ tus          ┆ d            │
│ i32    ┆ str       ┆ str  ┆ i32  ┆   ┆ ---          ┆ y            ┆ ---          ┆ ---          │
│        ┆           ┆      ┆      ┆   ┆ str          ┆ ---          ┆ str          ┆ datetime[μs, │
│        ┆           ┆      ┆      ┆   ┆              ┆ str          ┆              ┆ UTC]         │
╞════════╪═══════════╪══════╪══════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 2024   ┆ REG       ┆ ARI  ┆ 1    ┆ … ┆ Oblique      ┆ null         ┆ Did Not      ┆ 2024-09-06   │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ Participate  ┆ 19:05:30 UTC │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ In Practic…  ┆              │
│ 2024   ┆ REG       ┆ ARI  ┆ 1    ┆ … ┆ Back         ┆ null         ┆ Limited Part ┆ 2024-09-06   │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ icipation in ┆ 19:05:21 UTC │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ Pract…       ┆              │
│ 2024   ┆ REG       ┆ ARI  ┆ 1    ┆ … ┆ Ankle        ┆ null         ┆ Limited Part ┆ 2024-09-06   │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ icipation in ┆ 19:05:21 UTC │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ Pract…       ┆              │
│ 2024   ┆ REG       ┆ ATL  ┆ 1    ┆ … ┆ Not injury   ┆ null         ┆ Did Not      ┆ 2024-09-06   │
│        ┆           ┆      ┆      ┆   ┆ related -    ┆              ┆ Participate  ┆ 18:35:04 UTC │
│        ┆           ┆      ┆      ┆   ┆ resting p…   ┆              ┆ In Practic…  ┆              │
│ 2024   ┆ REG       ┆ ATL  ┆ 1    ┆ … ┆ Not injury   ┆ null         ┆ Did Not      ┆ 2024-09-06   │
│        ┆           ┆      ┆      ┆   ┆ related -    ┆              ┆ Participate  ┆ 18:35:48 UTC │
│        ┆           ┆      ┆      ┆   ┆ resting p…   ┆              ┆ In Practic…  ┆              │
│ …      ┆ …         ┆ …    ┆ …    ┆ … ┆ …            ┆ …            ┆ …            ┆ …            │
│ 2024   ┆ SB        ┆ PHI  ┆ 22   ┆ … ┆ Hamstring    ┆ null         ┆ Limited Part ┆ 2025-02-07   │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ icipation in ┆ 20:29:05 UTC │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ Pract…       ┆              │
│ 2024   ┆ SB        ┆ PHI  ┆ 22   ┆ … ┆ Neck         ┆ null         ┆ Full Partici ┆ 2025-02-07   │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ pation in    ┆ 20:32:07 UTC │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ Practice     ┆              │
│ 2024   ┆ SB        ┆ PHI  ┆ 22   ┆ … ┆ Elbow        ┆ null         ┆ Full Partici ┆ 2025-02-07   │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ pation in    ┆ 20:31:06 UTC │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ Practice     ┆              │
│ 2024   ┆ SB        ┆ PHI  ┆ 22   ┆ … ┆ Abdomen      ┆ null         ┆ Full Partici ┆ 2025-02-07   │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ pation in    ┆ 20:31:06 UTC │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ Practice     ┆              │
│ 2024   ┆ SB        ┆ PHI  ┆ 22   ┆ … ┆ Groin        ┆ null         ┆ Limited Part ┆ 2025-02-07   │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ icipation in ┆ 20:31:06 UTC │
│        ┆           ┆      ┆      ┆   ┆              ┆              ┆ Pract…       ┆              │
└────────┴───────────┴──────┴──────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘

In [6]:
depth_charts

shape: (37_312, 15)
┌────────┬───────────┬──────┬───────────┬───┬──────────┬───────────┬───────────────┬───────────────┐
│ season ┆ club_code ┆ week ┆ game_type ┆ … ┆ position ┆ elias_id  ┆ depth_positio ┆ full_name     │
│ ---    ┆ ---       ┆ ---  ┆ ---       ┆   ┆ ---      ┆ ---       ┆ n             ┆ ---           │
│ i32    ┆ str       ┆ i32  ┆ str       ┆   ┆ str      ┆ str       ┆ ---           ┆ str           │
│        ┆           ┆      ┆           ┆   ┆          ┆           ┆ str           ┆               │
╞════════╪═══════════╪══════╪═══════════╪═══╪══════════╪═══════════╪═══════════════╪═══════════════╡
│ 2024   ┆ ATL       ┆ 1    ┆ REG       ┆ … ┆ G        ┆ LIN451080 ┆ RG            ┆ Chris         │
│        ┆           ┆      ┆           ┆   ┆          ┆           ┆               ┆ Lindstrom     │
│ 2024   ┆ ATL       ┆ 1    ┆ REG       ┆ … ┆ G        ┆ HIN747075 ┆ RG            ┆ Kyle Hinton   │
│ 2024   ┆ ATL       ┆ 1    ┆ REG       ┆ … ┆ T        ┆ NOR763430 ┆ RT            ┆ Storm Norton  │
│ 2024   ┆ ATL       ┆ 1    ┆ REG       ┆ … ┆ TE       ┆ DWE397627 ┆ TE            ┆ Ross Dwelley  │
│ 2024   ┆ ATL       ┆ 1    ┆ REG       ┆ … ┆ RB       ┆ ROB368260 ┆ RB            ┆ Bijan         │
│        ┆           ┆      ┆           ┆   ┆          ┆           ┆               ┆ Robinson      │
│ …      ┆ …         ┆ …    ┆ …         ┆ … ┆ …        ┆ …         ┆ …             ┆ …             │
│ 2024   ┆ HOU       ┆ 21   ┆ CON       ┆ … ┆ DE       ┆ HUN529240 ┆ DE            ┆ Danielle      │
│        ┆           ┆      ┆           ┆   ┆          ┆           ┆               ┆ Hunter        │
│ 2024   ┆ HOU       ┆ 21   ┆ CON       ┆ … ┆ ILB      ┆ ALS107778 ┆ LB            ┆ Azeez         │
│        ┆           ┆      ┆           ┆   ┆          ┆           ┆               ┆ Al-Shaair     │
│ 2024   ┆ HOU       ┆ 21   ┆ CON       ┆ … ┆ CB       ┆ BOY229979 ┆ CB            ┆ Kris Boyd     │
│ 2024   ┆ HOU       ┆ 21   ┆ CON       ┆ … ┆ SS       ┆ STE793185 ┆ S             ┆ M.J. Stewart  │
│ 2024   ┆ HOU       ┆ 21   ┆ CON       ┆ … ┆ K        ┆ FAI144264 ┆ K             ┆ Ka'imi        │
│        ┆           ┆      ┆           ┆   ┆          ┆           ┆               ┆ Fairbairn     │
└────────┴───────────┴──────┴───────────┴───┴──────────┴───────────┴───────────────┴───────────────┘